#!/usr/bin/env bun
/**
 * Deterministic provider capability matrix generator.
 *
 * Reads `providers/*.json` from a source root and renders a bounded markdown
 * section into `docs/compatibility-matrix.md` (or an alternate output). The
 * output is fully deterministic: no timestamps, no host paths, no network. The
 * generated region is delimited by stable markers so hand-written doc content
 * around it is preserved.
 */

import fs from "node:fs";
import path from "node:path";
import { concreteProviderIds, readProviderCapabilities, type ProviderCapability } from "../modules/skillpool/providers.ts";

export const MATRIX_BEGIN = "<!-- BEGIN GENERATED PROVIDER MATRIX -->";
export const MATRIX_END = "<!-- END GENERATED PROVIDER MATRIX -->";
const GENERATED_NOTE =
  "<!-- Generated by scripts/commands/generate-provider-matrix.ts. Do not edit by hand. -->";

const REPO_ROOT = path.resolve(__dirname, "../..");
const DEFAULT_OUTPUT = path.join(REPO_ROOT, "docs", "compatibility-matrix.md");
const SCOPES = ["project", "user", "global"] as const;
type Scope = (typeof SCOPES)[number];

// Stable column order mirroring schema/provider.schema.json supports.properties.
const SUPPORT_KEYS = [
  "description",
  "skillMd",
  "implicitInvocationPolicy",
  "allowedTools",
  "permissions",
  "agentMode",
  "subagents",
  "disableModelInvocation",
  "userInvocable",
] as const;

export interface MatrixArgs {
  source: string;
  output: string;
  check: boolean;
  help: boolean;
}

function help(): void {
  console.log(`
Generate or check the provider capability matrix docs section

Usage:
  bun scripts/commands/generate-provider-matrix.ts [options]

Options:
  --source <dir>   Source root containing providers/*.json (default: repo root)
  --output <path>  Target markdown file, or "-" for stdout
                   (default: docs/compatibility-matrix.md)
  --check          Verify the bounded section is in sync; exit 1 if not
  --help           Show help
`);
}

export function parseArgs(argv: string[] = process.argv): MatrixArgs {
  const args: MatrixArgs = {
    source: REPO_ROOT,
    output: DEFAULT_OUTPUT,
    check: false,
    help: false,
  };

  for (let i = 2; i < argv.length; i += 1) {
    const token = argv[i]!;
    if (token === "--help" || token === "-h") {
      args.help = true;
      continue;
    }
    if (token === "--check") {
      args.check = true;
      continue;
    }
    if (token === "--source") {
      const value = argv[i + 1];
      if (!value) {
        throw new Error("Missing value for --source");
      }
      args.source = path.resolve(value);
      i += 1;
      continue;
    }
    if (token === "--output") {
      const value = argv[i + 1];
      if (!value) {
        throw new Error("Missing value for --output");
      }
      args.output = value;
      i += 1;
      continue;
    }
    throw new Error(`Unknown option: ${token}`);
  }

  return args;
}

function cell(value: string | undefined): string {
  return value ? `\`${value}\`` : "—";
}

function supportCell(supports: Record<string, boolean>, key: string): string {
  return supports[key] === true ? "yes" : "no";
}

function tableRow(cells: string[]): string {
  return `| ${cells.join(" | ")} |`;
}

// Discover provider manifests present in <sourceRoot>/providers, preserving the
// canonical provider id order. Falls back to the full canonical set so the tool
// fails loudly (via readProviderCapabilities) when expected manifests are absent.
function discoverProviderIds(sourceRoot: string): string[] {
  const providersDir = path.join(sourceRoot, "providers");
  if (!fs.existsSync(providersDir)) {
    return concreteProviderIds();
  }
  const present = new Set(
    fs
      .readdirSync(providersDir)
      .filter((file) => file.endsWith(".json"))
      .map((file) => file.replace(/\.json$/, "")),
  );
  return concreteProviderIds().filter((id) => present.has(id));
}

function scopePath(
  record: ProviderCapability,
  kind: "skillPaths" | "detectionPaths",
  scope: Scope,
): string | undefined {
  if (kind === "skillPaths") {
    return record.skillPaths[scope];
  }
  return record.detectionPaths ? record.detectionPaths[scope] : undefined;
}

export function generateMatrixBody(sourceRoot: string): string {
  const providers = readProviderCapabilities(sourceRoot, discoverProviderIds(sourceRoot));
  const lines: string[] = [];

  lines.push(GENERATED_NOTE);
  lines.push("");
  lines.push("## Provider Capability Matrix");
  lines.push("");

  lines.push("| Provider | Display name | Project skills | User skills | Global skills |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const provider of providers) {
    const id = `\`${provider.provider}\``;
    const name = provider.displayName || provider.provider;
    lines.push(
      tableRow([
        id,
        name,
        cell(scopePath(provider, "skillPaths", "project")),
        cell(scopePath(provider, "skillPaths", "user")),
        cell(scopePath(provider, "skillPaths", "global")),
      ]),
    );
  }
  lines.push("");

  lines.push("### Detection paths");
  lines.push("");
  lines.push("| Provider | Project | User | Global |");
  lines.push("| --- | --- | --- | --- |");
  for (const provider of providers) {
    const id = `\`${provider.provider}\``;
    lines.push(
      tableRow([
        id,
        cell(scopePath(provider, "detectionPaths", "project")),
        cell(scopePath(provider, "detectionPaths", "user")),
        cell(scopePath(provider, "detectionPaths", "global")),
      ]),
    );
  }
  lines.push("");

  lines.push("### Support flags");
  lines.push("");
  lines.push(`| Provider | ${SUPPORT_KEYS.join(" | ")} |`);
  lines.push(`| --- | ${SUPPORT_KEYS.map(() => "---").join(" | ")} |`);
  for (const provider of providers) {
    const id = `\`${provider.provider}\``;
    lines.push(tableRow([id, ...SUPPORT_KEYS.map((key) => supportCell(provider.supports, key))]));
  }
  lines.push("");

  lines.push("### Danger notes");
  lines.push("");
  for (const provider of providers) {
    lines.push(`#### ${provider.provider}`);
    lines.push("");
    if (provider.dangerNotes.length === 0) {
      lines.push("- _none_");
    } else {
      for (const note of provider.dangerNotes) {
        lines.push(`- ${note}`);
      }
    }
    lines.push("");
  }

  // Trim trailing blank lines but keep a single trailing newline handled by the
  // section wrapper. Return without a trailing newline for stable composition.
  return lines.join("\n").replace(/\n+$/, "");
}

export function renderMatrixSection(sourceRoot: string): string {
  return `${MATRIX_BEGIN}\n${generateMatrixBody(sourceRoot)}\n${MATRIX_END}`;
}

export function extractMatrixSection(content: string): string | null {
  const beginIndex = content.indexOf(MATRIX_BEGIN);
  if (beginIndex === -1) {
    return null;
  }
  const endIndex = content.indexOf(MATRIX_END, beginIndex);
  if (endIndex === -1) {
    return null;
  }
  return content.slice(beginIndex, endIndex + MATRIX_END.length);
}

export function injectMatrixSection(content: string, section: string): string {
  const existing = extractMatrixSection(content);
  if (existing === null) {
    const trimmed = content.replace(/\n+$/, "");
    return trimmed ? `${trimmed}\n\n${section}\n` : `${section}\n`;
  }
  return content.replace(existing, section);
}

export function checkMatrix(content: string, sourceRoot: string): boolean {
  const existing = extractMatrixSection(content);
  if (existing === null) {
    return false;
  }
  return existing === renderMatrixSection(sourceRoot);
}

function resolveOutputPath(rawOutput: string): string | null {
  if (rawOutput === "-") {
    return null;
  }
  if (path.isAbsolute(rawOutput)) {
    return rawOutput;
  }
  return path.resolve(process.cwd(), rawOutput);
}

export function main(argv: string[] = process.argv): void {
  const args = parseArgs(argv);
  if (args.help) {
    help();
    return;
  }

  const section = renderMatrixSection(args.source);

  if (args.check) {
    const outputPath = resolveOutputPath(args.output) ?? DEFAULT_OUTPUT;
    if (!fs.existsSync(outputPath)) {
      console.error(`ERROR: output file not found: ${outputPath}`);
      process.exitCode = 1;
      return;
    }
    const content = fs.readFileSync(outputPath, "utf8");
    if (!checkMatrix(content, args.source)) {
      console.error(`ERROR: provider matrix section out of sync in ${outputPath}`);
      console.error("Regenerate with: bun scripts/commands/generate-provider-matrix.ts");
      process.exitCode = 1;
      return;
    }
    console.log("STATUS: PASS");
    console.log("Provider matrix section is in sync.");
    return;
  }

  const outputPath = resolveOutputPath(args.output);
  if (outputPath === null) {
    console.log(section);
    return;
  }

  const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
  const next = injectMatrixSection(existing, section);
  fs.writeFileSync(outputPath, next, "utf8");
  console.log(`Wrote provider matrix section to ${outputPath}`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`ERROR: ${message}`);
    process.exit(1);
  }
}
